In [3]:
import pandas as pd

In [4]:
# df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], columns=["A", "B", "C"])
# df.index.to_list()

# print(df)
# df.info()
# df.describe()
# df.shape
# df["B"].unique()





coffee = pd.read_csv('./warmup-data/coffee.csv')
# print(coffee)

results = pd.read_parquet('./data/results.parquet')
# print(results)

olympics = pd.read_excel('./data/olympics-data.xlsx')
# print(olympics)

feather = pd.read_feather('./data/results.feather')
# print(feather)


coffee.tail()

         Day Coffee Type  Units Sold
9     Friday       Latte          35
10  Saturday    Espresso          45
11  Saturday       Latte          35
12    Sunday    Espresso          45
13    Sunday       Latte          35

In [5]:
coffee = coffee.reset_index(drop=True)

In [ ]:
# coffee.loc[:,["Day","Coffee Type"]]   # loc is inclusive of the last index.It defines the index of the rows to be selected. It is label based indexing.

# coffee.loc["Monday":"Wednesday","Units Sold"] # to check if the index has been set to Day or not.

Day
Monday       25
Monday       15
Tuesday      30
Tuesday      20
Wednesday    35
Wednesday    25
Name: Units Sold, dtype: int64

In [6]:
coffee.iloc[0:12,[0,2]] # iloc is exclusive of the last index. It defines the index of the rows to be selected. It is integer based indexing.

          Day  Units Sold
0      Monday          25
1      Monday          15
2     Tuesday          30
3     Tuesday          20
4   Wednesday          35
5   Wednesday          25
6    Thursday          40
7    Thursday          30
8      Friday          45
9      Friday          35
10   Saturday          45
11   Saturday          35

In [9]:
coffee.loc[1,"Units Sold"] = 10
print(coffee)

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          10
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [13]:
coffee.sort_values(["Units Sold","Coffee Type"],ascending=False)

          Day Coffee Type  Units Sold
8      Friday    Espresso          45
10   Saturday    Espresso          45
12     Sunday    Espresso          45
6    Thursday    Espresso          40
9      Friday       Latte          35
11   Saturday       Latte          35
13     Sunday       Latte          35
4   Wednesday    Espresso          35
7    Thursday       Latte          30
2     Tuesday    Espresso          30
5   Wednesday       Latte          25
0      Monday    Espresso          25
3     Tuesday       Latte          20
1      Monday       Latte          10

In [ ]:
# for index,rows in coffee.iterrows():
#     print(index)
#     print(rows["Units Sold"])
#     print("\n\n")

0
25



1
10



2
30



3
20



4
35



5
25



6
40



7
30



8
45



9
35



10
45



11
35



12
45



13
35